### ISSUE TITLE
Summary-exceeds expectations

### ISSUE THREAD

**Issue by ghost** [Ghar1b/tea_cozy#4]
Great job! You have good indentation, alt attributes, and comments. As a next step, consider adding another page to the site with a text box for users to enter text in. I think you're ready for it!

**Comment by Ghar1b** [comment]
Thank you for motivating words and for your review. I'm eager to practice more. Do you know, if there is an open resource on the web, which provides more of the similar stuff (like tasks for websites with spec-sheets, which become gradually more complex?
